In [1]:
import pandas as pd
from pathlib import Path

## Concatenating pollutant files in one

In [2]:
raw_folder = Path("../data/raw")
processed_folder = Path("../data/processed")

# Year to process
year = 2023

In [3]:
'''
# Concatenate all CSV files into one, filtering for "ZAG PARIS"
# Chunk size to limit RAM usage
chunk_size = 1_000_000
# Flag to write header only for the first chunk
first_chunk = True

# Iterate over all CSV files
for csv_file in sorted(raw_folder.glob(f"FR_E2_{year}-*.csv")):
    # Read and filter in chunks
    for chunk in pd.read_csv(csv_file, sep=";", chunksize=chunk_size):
        filtered = chunk[chunk["Zas"] == "ZAG PARIS"]
        # Progressive writing to the output CSV
        filtered.to_csv(
            processed_folder / f"data_air_quality_{year}.csv",
            sep=";",
            index=False,
            header=first_chunk,
            mode="w" if first_chunk else "a"
        )
        first_chunk = False

print("Final CSV :", processed_folder / f"data_air_quality_{year}.csv")
'''

'\n# Concatenate all CSV files into one, filtering for "ZAG PARIS"\n# Chunk size to limit RAM usage\nchunk_size = 1_000_000\n# Flag to write header only for the first chunk\nfirst_chunk = True\n\n# Iterate over all CSV files\nfor csv_file in sorted(raw_folder.glob(f"FR_E2_{year}-*.csv")):\n    # Read and filter in chunks\n    for chunk in pd.read_csv(csv_file, sep=";", chunksize=chunk_size):\n        filtered = chunk[chunk["Zas"] == "ZAG PARIS"]\n        # Progressive writing to the output CSV\n        filtered.to_csv(\n            processed_folder / f"data_air_quality_{year}.csv",\n            sep=";",\n            index=False,\n            header=first_chunk,\n            mode="w" if first_chunk else "a"\n        )\n        first_chunk = False\n\nprint("Final CSV :", processed_folder / f"data_air_quality_{year}.csv")\n'

In [3]:
df_2021 = pd.read_csv(Path("../data/processed/data_air_quality_2021.csv"), sep=";")
df_2021.shape

(1305096, 23)

In [4]:
df_2021.head()

,Date de début,Date de fin,Organisme,code zas,Zas,code site,nom site,type d'implantation,Polluant,type d'influence,...,procédure de mesure,type de valeur,valeur,valeur brute,unité de mesure,taux de saisie,couverture temporelle,couverture de données,code qualité,validité
0,2021/01/01 00:00:00,2021/01/01 01:00:00,AIRPARIF,FR11ZAG01,ZAG PARIS,FR04002,GENNEVILLIERS,Urbaine,NO,Fond,...,Auto NO app AC32M,moyenne horaire validée,25.0,25.025,µg-m3,NaN,NaN,NaN,A,1
1,2021/01/01 01:00:00,2021/01/01 02:00:00,AIRPARIF,FR11ZAG01,ZAG PARIS,FR04002,GENNEVILLIERS,Urbaine,NO,Fond,...,Auto NO app AC32M,moyenne horaire validée,26.4,26.375,µg-m3,NaN,NaN,NaN,A,1
2,2021/01/01 02:00:00,2021/01/01 03:00:00,AIRPARIF,FR11ZAG01,ZAG PARIS,FR04002,GENNEVILLIERS,Urbaine,NO,Fond,...,Auto NO app AC32M,moyenne horaire validée,21.8,21.825,µg-m3,NaN,NaN,NaN,A,1
3,2021/01/01 03:00:00,2021/01/01 04:00:00,AIRPARIF,FR11ZAG01,ZAG PARIS,FR04002,GENNEVILLIERS,Urbaine,NO,Fond,...,Auto NO app AC32M,moyenne horaire validée,20.1,20.050,µg-m3,NaN,NaN,NaN,A,1
4,2021/01/01 04:00:00,2021/01/01 05:00:00,AIRPARIF,FR11ZAG01,ZAG PARIS,FR04002,GENNEVILLIERS,Urbaine,NO,Fond,...,Auto NO app AC32M,moyenne horaire validée,23.3,23.300,µg-m3,NaN,NaN,NaN,A,1

# Filtering weather dataset

In [21]:
df_weather = pd.read_csv(Path("../data/raw/Q_75_previous-1950-2024_RR-T-Vent.csv"), sep=";")
df_weather_ap = pd.read_csv(Path("../data/raw/Q_75_previous-1950-2024_autres-parametres.csv"), sep=";")

In [22]:
# Filtering on column AAAAMMJJ for years 2021 to 2023
df_weather = df_weather[df_weather["AAAAMMJJ"].between(20210101, 20231231)]
df_weather_ap = df_weather_ap[df_weather_ap["AAAAMMJJ"].between(20210101, 20231231)]

In [8]:
# Writing filtered weather data to new CSV files
# df_weather.to_csv(Path("../data/processed/data_weather.csv"), sep=";", index=False)
# df_weather_ap.to_csv(Path("../data/processed/data_weather_ap.csv"), sep=";", index=False)

In [23]:
df_weather["AAAAMMJJ"] = pd.to_datetime(df_weather['AAAAMMJJ'].astype(str), format="%Y%m%d")
df_weather.rename(columns={'AAAAMMJJ':'Date'}, inplace=True)

df_weather_ap["AAAAMMJJ"] = pd.to_datetime(df_weather_ap["AAAAMMJJ"].astype(str), format="%Y%m%d")
df_weather_ap.rename(columns={"AAAAMMJJ": "Date"}, inplace=True)

df_weather_ap

,NUM_POSTE,NOM_USUEL,LAT,LON,ALTI,Date,DHUMEC,QDHUMEC,PMERM,QPMERM,...,ECLAIR,QECLAIR,NB300,QNB300,BA300,QBA300,TMERMIN,QTMERMIN,TMERMAX,QTMERMAX
12356,75106001,LUXEMBOURG,48.844667,2.333833,46,2021-01-01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12357,75106001,LUXEMBOURG,48.844667,2.333833,46,2021-01-02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12358,75106001,LUXEMBOURG,48.844667,2.333833,46,2021-01-03,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12359,75106001,LUXEMBOURG,48.844667,2.333833,46,2021-01-04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12360,75106001,LUXEMBOURG,48.844667,2.333833,46,2021-01-05,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132218,75116008,LONGCHAMP,48.854833,2.233667,27,2023-12-30,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132219,75116008,LONGCHAMP,48.854833,2.233667,27,2023-12-31,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145724,75119001,BUTTES CHAUMONT,48.876833,2.380833,97,2021-02-09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145725,75119001,BUTTES CHAUMONT,48.876833,2.380833,97,2021-11-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145726,75119001,BUTTES CHAUMONT,48.876833,2.380833,97,2022-12-05,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_weather_ap.groupby("NUM_POSTE")[["PMERM", "GLOT", "UM"]].count()

           PMERM  GLOT    UM
NUM_POSTE
75106001       0     0     0
75107005       0     0     0
75110001       0     0     0
75112001       0     0     0
75114001    1095  1095  1095
75114007       0     0     0
75116008       0  1094  1095
75119001       0     0     0

In [25]:
df_weather.groupby("NUM_POSTE")[["RR", "TNTXM", "FFM"]].count()

             RR  TNTXM   FFM
NUM_POSTE
75106001   1095   1095     0
75107005      0   1035  1035
75110001   1095   1095     0
75112001    335      0     0
75112004    761      0     0
75113002    730      0     0
75114001   1095   1095  1095
75114007      0   1095     0
75116002    425      0     0
75116008   1095   1095  1091
75119001    761      0     0

In [26]:
df_weather = df_weather[["Date", "RR", "TNTXM", "FFM"]]
df_weather_ap = df_weather_ap[["Date", "PMERM", "GLOT", "UM"]]
df_weather_ap

             Date  PMERM   GLOT    UM
12356  2021-01-01    NaN    NaN   NaN
12357  2021-01-02    NaN    NaN   NaN
12358  2021-01-03    NaN    NaN   NaN
12359  2021-01-04    NaN    NaN   NaN
12360  2021-01-05    NaN    NaN   NaN
...           ...    ...    ...   ...
132218 2023-12-30    NaN  217.0  85.0
132219 2023-12-31    NaN  411.0  72.0
145724 2021-02-09    NaN    NaN   NaN
145725 2021-11-23    NaN    NaN   NaN
145726 2022-12-05    NaN    NaN   NaN

[6532 rows x 4 columns]

In [27]:
df_weather_ap.isnull().sum()

Date        0
PMERM    5437
GLOT     4343
UM       4342
dtype: int64

In [ ]:
df_weather_daily = df_weather.groupby("Date")[["RR", "TNTXM", "FFM"]].mean().reset_index()

df_weather_ap_daily = df_weather_ap.groupby("Date")[["PMERM", "GLOT", "UM"]].mean().reset_index()
df_weather_ap_daily

           Date   PMERM   GLOT    UM
0    2021-01-01  1011.3  386.0  83.0
1    2021-01-02  1014.8  465.0  88.0
2    2021-01-03  1014.2  194.5  84.0
3    2021-01-04  1013.6   64.0  82.5
4    2021-01-05  1014.9   48.5  84.0
...         ...     ...    ...   ...
1090 2023-12-27  1016.3  346.5  72.5
1091 2023-12-28  1017.1  277.0  83.5
1092 2023-12-29  1015.8  235.5  84.0
1093 2023-12-30  1013.4  186.5  87.0
1094 2023-12-31  1002.3  429.0  73.0

[1095 rows x 4 columns]

In [ ]:
# df_weather_daily.to_csv(Path("../data/processed/data_weather_filtered.csv"), sep=";", index=False)
# df_weather_ap_daily.to_csv(Path("../data/processed/data_weather_ap_filtered.csv"), sep=";", index=False)

## Merging the two weather datasets together

In [29]:
df_weather_daily_full = pd.merge(df_weather_daily, df_weather_ap_daily, on="Date", how="outer")
df_weather_daily_full

           Date        RR      TNTXM       FFM   PMERM   GLOT    UM
0    2021-01-01  0.055556   1.833333  2.033333  1011.3  386.0  83.0
1    2021-01-02  0.088889   1.566667  1.600000  1014.8  465.0  88.0
2    2021-01-03  0.088889   3.083333  3.000000  1014.2  194.5  84.0
3    2021-01-04  0.100000   2.816667  4.533333  1013.6   64.0  82.5
4    2021-01-05  0.144444   2.566667  4.266667  1014.9   48.5  84.0
...         ...       ...        ...       ...     ...    ...   ...
1090 2023-12-27  0.100000   9.550000  6.466667  1016.3  346.5  72.5
1091 2023-12-28  0.000000  10.500000  5.300000  1017.1  277.0  83.5
1092 2023-12-29  0.400000  10.433333  6.500000  1015.8  235.5  84.0
1093 2023-12-30  0.900000   9.216667  6.066667  1013.4  186.5  87.0
1094 2023-12-31  0.050000   9.650000  8.466667  1002.3  429.0  73.0

[1095 rows x 7 columns]

# Merging dataset with weather variables

In [30]:
df_o3 = pd.read_csv(Path("../data/processed/merged_o3_trafic.csv"), index_col=0)
df_pm10 = pd.read_csv(Path("../data/processed/merged_pm10_trafic.csv"), index_col=0)

In [15]:
df_o3

,date_fin,code_site,polluant,concentration,avg_debit,avg_taux_occup
0,2021-01-01 01:00:00,FR04004,O3,3.1,214.412018,1.476789
1,2021-01-01 02:00:00,FR04004,O3,2.8,210.467804,1.366031
2,2021-01-01 03:00:00,FR04004,O3,2.7,194.788788,1.129716
3,2021-01-01 04:00:00,FR04004,O3,2.6,185.128754,1.151880
4,2021-01-01 05:00:00,FR04004,O3,2.6,193.754303,1.152384
...,...,...,...,...,...,...
103865,2023-12-31 20:00:00,FR04055,O3,59.2,600.233826,10.621044
103866,2023-12-31 21:00:00,FR04055,O3,57.0,599.395325,9.847783
103867,2023-12-31 22:00:00,FR04055,O3,51.0,554.399475,7.781728
103868,2023-12-31 23:00:00,FR04055,O3,55.6,533.588013,7.630075
103869,2024-01-01 00:00:00,FR04055,O3,52.6,500.903900,7.391140

In [31]:
df_o3['date_fin'] = pd.to_datetime(df_o3['date_fin']) - pd.Timedelta(hours=1)
df_pm10['date_fin'] = pd.to_datetime(df_pm10['date_fin']) - pd.Timedelta(hours=1)

In [32]:
# Creating new column date for merging
df_o3["Date"] = pd.to_datetime(df_o3["date_fin"]).dt.date
df_o3["Date"] = pd.to_datetime(df_o3["Date"])

df_pm10["Date"] = pd.to_datetime(df_pm10["date_fin"]).dt.date
df_pm10["Date"] = pd.to_datetime(df_pm10["Date"])

In [18]:
df_o3

,date_fin,code_site,polluant,concentration,avg_debit,avg_taux_occup,Date
0,2021-01-01 00:00:00,FR04004,O3,3.1,214.412018,1.476789,2021-01-01
1,2021-01-01 01:00:00,FR04004,O3,2.8,210.467804,1.366031,2021-01-01
2,2021-01-01 02:00:00,FR04004,O3,2.7,194.788788,1.129716,2021-01-01
3,2021-01-01 03:00:00,FR04004,O3,2.6,185.128754,1.151880,2021-01-01
4,2021-01-01 04:00:00,FR04004,O3,2.6,193.754303,1.152384,2021-01-01
...,...,...,...,...,...,...,...
103865,2023-12-31 19:00:00,FR04055,O3,59.2,600.233826,10.621044,2023-12-31
103866,2023-12-31 20:00:00,FR04055,O3,57.0,599.395325,9.847783,2023-12-31
103867,2023-12-31 21:00:00,FR04055,O3,51.0,554.399475,7.781728,2023-12-31
103868,2023-12-31 22:00:00,FR04055,O3,55.6,533.588013,7.630075,2023-12-31
103869,2023-12-31 23:00:00,FR04055,O3,52.6,500.903900,7.391140,2023-12-31

In [33]:
# Merging df_o3 and df_pm10 with df_weather on "Date"

df_merged_o3 = pd.merge(df_o3, df_weather_daily_full, on="Date", how="left")
df_merged_o3.drop(columns=["Date"], inplace=True)

df_merged_pm10 = pd.merge(df_pm10, df_weather_daily_full, on="Date", how="left")
df_merged_pm10.drop(columns=["Date"], inplace=True)

In [35]:
df_merged_o3.head(30)

,date_fin,code_site,polluant,concentration,avg_debit,avg_taux_occup,RR,TNTXM,FFM,PMERM,GLOT,UM
0,2021-01-01 00:00:00,FR04004,O3,3.1,214.412018,1.476789,0.055556,1.833333,2.033333,1011.3,386.0,83.0
1,2021-01-01 01:00:00,FR04004,O3,2.8,210.467804,1.366031,0.055556,1.833333,2.033333,1011.3,386.0,83.0
2,2021-01-01 02:00:00,FR04004,O3,2.7,194.788788,1.129716,0.055556,1.833333,2.033333,1011.3,386.0,83.0
3,2021-01-01 03:00:00,FR04004,O3,2.6,185.128754,1.151880,0.055556,1.833333,2.033333,1011.3,386.0,83.0
4,2021-01-01 04:00:00,FR04004,O3,2.6,193.754303,1.152384,0.055556,1.833333,2.033333,1011.3,386.0,83.0
5,2021-01-01 05:00:00,FR04004,O3,3.3,212.995697,1.251761,0.055556,1.833333,2.033333,1011.3,386.0,83.0
6,2021-01-01 06:00:00,FR04004,O3,4.7,348.316010,1.905362,0.055556,1.833333,2.033333,1011.3,386.0,83.0
7,2021-01-01 07:00:00,FR04004,O3,7.5,328.891907,1.803650,0.055556,1.833333,2.033333,1011.3,386.0,83.0
8,2021-01-01 08:00:00,FR04004,O3,7.8,280.896118,1.678810,0.055556,1.833333,2.033333,1011.3,386.0,83.0
9,2021-01-01 09:00:00,FR04004,O3,17.5,309.147186,2.093955,0.055556,1.833333,2.033333,1011.3,386.0,83.0
10,2021-01-01 10:00:00,FR04004,O3,27.3,417.259735,2.405444,0.055556,1.833333,2.033333,1011.3,386.0,83.0
11,2021-01-01 11:00:00,FR04004,O3,27.4,625.350647,3.464082,0.055556,1.833333,2.033333,1011.3,386.0,83.0
12,2021-01-01 12:00:00,FR04004,O3,27.8,798.588745,4.746730,0.055556,1.833333,2.033333,1011.3,386.0,83.0
13,2021-01-01 13:00:00,FR04004,O3,29.1,802.194824,4.827389,0.055556,1.833333,2.033333,1011.3,386.0,83.0
14,2021-01-01 14:00:00,FR04004,O3,35.0,868.251099,5.472339,0.055556,1.833333,2.033333,1011.3,386.0,83.0
15,2021-01-01 15:00:00,FR04004,O3,29.4,927.567078,6.315287,0.055556,1.833333,2.033333,1011.3,386.0,83.0
16,2021-01-01 16:00:00,FR04004,O3,22.6,971.359314,6.612805,0.055556,1.833333,2.033333,1011.3,386.0,83.0
17,2021-01-01 17:00:00,FR04004,O3,13.1,1025.532471,6.941949,0.055556,1.833333,2.033333,1011.3,386.0,83.0
18,2021-01-01 18:00:00,FR04004,O3,7.5,1069.536743,7.094479,0.055556,1.833333,2.033333,1011.3,386.0,83.0
19,2021-01-01 19:00:00,FR04004,O3,3.0,1038.008667,6.236323,0.055556,1.833333,2.033333,1011.3,386.0,83.0
20,2021-01-01 20:00:00,FR04004,O3,2.3,635.510803,3.559099,0.055556,1.833333,2.033333,1011.3,386.0,83.0
21,2021-01-01 21:00:00,FR04004,O3,4.2,390.268402,1.997699,0.055556,1.833333,2.033333,1011.3,386.0,83.0
22,2021-01-01 22:00:00,FR04004,O3,3.9,297.072968,1.552871,0.055556,1.833333,2.033333,1011.3,386.0,83.0
23,2021-01-01 23:00:00,FR04004,O3,2.5,216.383621,1.100298,0.055556,1.833333,2.033333,1011.3,386.0,83.0
24,2021-01-02 00:00:00,FR04004,O3,2.1,166.790604,0.905070,0.088889,1.566667,1.600000,1014.8,465.0,88.0
25,2021-01-02 01:00:00,FR04004,O3,1.5,128.051727,0.700561,0.088889,1.566667,1.600000,1014.8,465.0,88.0
26,2021-01-02 02:00:00,FR04004,O3,2.1,98.258621,0.482501,0.088889,1.566667,1.600000,1014.8,465.0,88.0
27,2021-01-02 03:00:00,FR04004,O3,1.6,404.361115,0.731944,0.088889,1.566667,1.600000,1014.8,465.0,88.0
28,2021-01-02 04:00:00,FR04004,O3,1.4,116.604347,0.556272,0.088889,1.566667,1.600000,1014.8,465.0,88.0
29,2021-01-02 05:00:00,FR04004,O3,1.9,181.170303,0.934790,0.088889,1.566667,1.600000,1014.8,465.0,88.0

In [36]:
df_merged_o3.duplicated().sum()

np.int64(0)

In [37]:
df_merged_o3["date"] = df_merged_o3["date_fin"].dt.floor("D")
df_merged_pm10["date"] = df_merged_pm10["date_fin"].dt.floor("D")

In [22]:
# df_merged_o3.to_csv(Path("../data/processed/merged_o3_trafic_weather.csv"), index=False)
# df_merged_pm10.to_csv(Path("../data/processed/merged_pm10_trafic_weather.csv"), index=False)

# Creating dataset with daily observations

In [38]:
# Group dataset by day and calculate mean for each day
df_merged_o3_daily = df_merged_o3.groupby(["date", "code_site"]).agg({
    "concentration": "max",
    "avg_debit": "mean",
    "avg_taux_occup": "mean",
    "RR": "mean",
    "TNTXM": "mean",
    "FFM": "mean",
    "PMERM": "mean",
    "GLOT": "mean",
    "UM": "mean"
}).reset_index()

df_merged_pm10_daily = (
    df_merged_pm10.groupby(["date", "code_site"])[["concentration", "avg_debit", "avg_taux_occup", "RR", "TNTXM", "FFM", "PMERM", "GLOT", "UM"]]
    .mean()
    .reset_index()
)

In [39]:
df_merged_o3_daily

,date,code_site,concentration,avg_debit,avg_taux_occup,RR,TNTXM,FFM,PMERM,GLOT,UM
0,2021-01-01,FR04004,35.0,523.403488,3.222381,0.055556,1.833333,2.033333,1011.3,386.0,83.0
1,2021-01-01,FR04017,34.9,494.989194,2.114353,0.055556,1.833333,2.033333,1011.3,386.0,83.0
2,2021-01-01,FR04037,37.1,450.788817,2.498502,0.055556,1.833333,2.033333,1011.3,386.0,83.0
3,2021-01-01,FR04055,40.4,261.828871,2.365695,0.055556,1.833333,2.033333,1011.3,386.0,83.0
4,2021-01-02,FR04004,10.7,658.445692,5.319976,0.088889,1.566667,1.600000,1014.8,465.0,88.0
...,...,...,...,...,...,...,...,...,...,...,...
4351,2023-12-30,FR04055,55.9,469.473481,6.305843,0.900000,9.216667,6.066667,1013.4,186.5,87.0
4352,2023-12-31,FR04004,84.6,1015.223434,6.947408,0.050000,9.650000,8.466667,1002.3,429.0,73.0
4353,2023-12-31,FR04017,83.6,786.605914,6.214364,0.050000,9.650000,8.466667,1002.3,429.0,73.0
4354,2023-12-31,FR04037,82.8,690.260033,4.646041,0.050000,9.650000,8.466667,1002.3,429.0,73.0
4355,2023-12-31,FR04055,81.6,430.735652,5.769500,0.050000,9.650000,8.466667,1002.3,429.0,73.0

In [40]:
df_merged_o3_daily.to_csv(Path("../data/processed/merged_o3_trafic_weather_daily.csv"), index=False)
df_merged_pm10_daily.to_csv(Path("../data/processed/merged_pm10_trafic_weather_daily.csv"), index=False)